[package]
name = "cresmarmat-an/compressor"
version = "1.0.0"
description = "Binary serialization for Roblox."
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = ["Cresmar Mat-an"]
license = "MIT"

[dependencies]
